[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "tmux-256color"

[font]
size = 18.0

[font.bold]
family = "NotoSansMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Operator Mono"
style = "Bold Italic"

[font.italic]
family = "Operator Mono"
style = "Extra Light Italic"

[font.normal]
family = "NotoSansMono Nerd Font"
style = "ExtraLight"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "¼"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[mouse]
hide_when_typing = false

[scrolling]
history = 0

[window]
option_as_alt = "both"
decorations = "none"
opacity = 1.0
startup_mode = "Fullscreen"

[general]
live_config_reload = true
import = ["./rose-pine-moon.toml"]
