require "plugin.hydra_nvim.vim_options"
require "plugin.hydra_nvim.git"
require "plugin.hydra_nvim.lsp"
require "plugin.hydra_nvim.telescope"
require "plugin.hydra_nvim.terminal"
require "plugin.hydra_nvim.packer"
