# Don't print a new line at the start of the prompt
add_newline = false

# Use custom format
format = """
$username\
$hostname\
$directory\
${custom.system_icons} \
    ${custom.git}\
	    $package\
		$rust\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[custom.system_icons]
description = "Show system icons"
command     = '([ $(uname -s) == "Darwin" ] && echo ï…¹  ) || ([ $(uname -s) == "Linux" ] && echo ï…¼)  '
symbol      = "at"
format      = "[$symbol]() [$output]($style) "
style       = "bold"
shell       = ["bash", "--noprofile", "--norc"]
when        = true

[character]
success_symbol = "[Î»]($bold green)"
error_symbol = "[Î»]($bold fg:#fd6f6b)"

[directory]
disabled = false
read_only = "ðŸ”’ "
read_only_style = "red"
truncate_to_repo = false
truncation_length = 8
format = "[$read_only]($read_only_style)[$path](bold fg:#94bdff) "

[custom.git]
symbol = "on "
command = "print -P ${GITSTATUS_PROMPT}"
when = true

# Language Support
